### home
GET https://api.cashpayments.in/home/detail
Content-Type: application/json
X-Token: PAY_CLIENT_tj7warc4rp_100093



### generateQRCode
GET https://api.cashpayments.in/client/generateQRCode
Content-Type: application/json
X-Token: PAY_CLIENT_tj7warc4rp_100093

### address
GET https://api.cashpayments.in/recharge/system/address
Content-Type: application/json
X-Token: PAY_CLIENT_ax8lv8c814_100093


### bind
POSt https://api.cashpayments.in/client/bind/google/code
Content-Type: application/json
X-Token: PAY_CLIENT_tj7warc4rp_100093

{
  "googleCode": 191914
}


### bind
POSt https://api.cashpayments.in/recharge/usdt
Content-Type: application/json
X-Token: PAY_CLIENT_tj7warc4rp_100093

{
  "amount": 0,
  "myAddressId": 6,
  "systemAddressId": 0,
  "googleCode": 191914
}

