<route lang="yaml">
meta:
  title: auth
  hideHeader: true
  hideFooter: true
</route>

<script lang="ts" setup>
import { Toast } from 'vant'
import { bind, generateQRCode } from '@/apis/home'
const router = useRouter()

const secretKey = ref('')
const qrUrl = ref('')
const googleCode = ref()

const onBind = () => {
  bind({ googleCode: googleCode.value }).then((res) => {
    if (res.code === 200) {
      Toast('提交成功')
      router.go(-1)
    }
    else {
      Toast(res.message)
    }
  })
}

onMounted(() => {
  generateQRCode().then((res) => {
    if (res.code === 200) {
      qrUrl.value = res.data.qrUrl
      secretKey.value = res.data.secretKey
    }
    else {
      Toast(res.message)
    }
  })
})
</script>

<template>
  <header bg-primary color-white leading-10 pl-3>
    <VanIcon name="arrow-left" @click="router.go(-1)" />
  </header>
  <div class="Auth p-4 bg-gray-1 flex-1">
    <section>
      <p>1.Download Google Authenticator</p>
      <p text-center my-4>
        <VanButton type="primary" size="small">
          Download Now
        </VanButton>
      </p>
    </section>
    <hr my-4 />
    <section>
      <p>2.Open the Google Authenticator and scanthe QR Code below or enter secretKey</p>
      <p text-center my-4>
        <img inline-block crossorigin="anonymous" :src="qrUrl" alt="二维码" />
      </p>
      <p font-bold>
        secretKey
      </p>
      <p text-sm>
        {{ secretKey }}
      </p>
    </section>
    <hr my-4 />
    <section>
      <p>
        3.Enter the time-based on-time codegenerated by the Google Authenticator appin the filed below
      </p>
      <p font-bold mt-2>
        Google Authenticator
      </p>
      <VanField
        v-model="googleCode"
        name="googleCode"
        label=""
        placeholder="Enter new Google Auth.code"
      />
    </section>
    <section my-4>
      <VanButton block type="primary" @click="onBind">
        Confirm
      </VanButton>
    </section>
  </div>
</template>

<style lang="less" scoped>
.Home {

  &-tag {
    line-height: 24px;
    font-size: 14px;
    border-top-left-radius: 20px;
    border-bottom-left-radius: 20px;
  }
}
</style>
